### ISSUE TITLE
Optional call grammar

### ISSUE THREAD

**Issue by waldemarhorwat** [tc39/proposal-optional-chaining#12]
The grammar allows
`a(b)?.(c)`
but prohibits
`a?.(b)`

Is that intentional?

**Comment by jridgewell** [comment]
That's explicitly allowed.

> https://github.com/tc39/proposal-optional-chaining#semantics

```js
a?.()        // a is invoked if not null/undefined

**Comment by waldemarhorwat** [comment]
The example allows it, but the grammar in the proposal doesn't allow it.

**Comment by jridgewell** [comment]
Seems to? https://claudepache.github.io/es-optional-chaining/#prod-CallExpression

**Comment by claudepache** [comment]
@waldemarhorwat It’s a bug. The following rule is missing:

```
CallExpression[Yield] :
    ...
    MemberExpression[?Yield] OptionalChainingOperator Arguments[?Yield]
    ...
```

**Comment by rattrayalex** [comment]
This is off-topic on the question at hand, but relates to the title of the thread – where can one read about the decision to go with `maybeFn?.(arg)` instead of `maybeFn?(arg)`? 

It was implied elsewhere that this debate had been had; it might be helpful to the community to have the explanation somewhere (perhaps I simply haven't found it).

**Comment by jridgewell** [comment]
> where can one read about the decision to go with `maybeFn?.(arg)` instead of `maybeFn?(arg)`?

https://github.com/tc39/proposal-optional-chaining/issues/5#issuecomment-311795543

**Comment by Mouvedia** [comment]
@rattrayalex that's because there was no *real* debate and both issues were closed too abruptly.

**Comment by claudepache** [comment]
@waldemarhorwat The bug is fixed with the latest update. Thanks for the careful reading.
